modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/Ametrin-Studios/Ametrin/issues" #optional

[[mods]] #mandatory
    modId="${mod_id}" #mandatory
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    updateJSONURL="https://raw.githubusercontent.com/Ametrin-Studios/Ametrin/master/update.json" #optional
    displayURL="https://www.curseforge.com/minecraft/mc-mods/ametrin" #optional
    #logoFile="examplemod.png" #optional
    #credits="" #optional
    authors="${mod_authors}" #optional
    #displayTest="MATCH_VERSION" #optional
    description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required"
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="${mod_id}.mixins.json"

[[accessTransformers]]
    file="${mod_id}.base.cfg"